'use client';

import React from 'react';
import { AlertTriangle, ChevronLeft } from 'lucide-react';

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-[#F9FBFF] text-[#1A1C1E] p-6 md:p-12">
      <div className="max-w-3xl mx-auto bg-white rounded-3xl p-8 md:p-12 shadow-xl border border-blue-50">
        <div className="flex items-center justify-between mb-12">
          <a href="/" className="flex items-center text-blue-600 hover:text-blue-700 font-medium group transition-all">
            <ChevronLeft className="mr-2 group-hover:-translate-x-1 transition-transform" />
            Back to Home
          </a>
          <AlertTriangle className="text-amber-500" size={32} />
        </div>

        <h1 className="text-4xl font-extrabold mb-8 tracking-tight">Medical Disclaimer</h1>
        <p className="text-gray-400 mb-8 font-medium italic">Last Updated: April 2026</p>

        <div className="prose prose-blue max-w-none space-y-8 text-gray-600 leading-relaxed">
          <section className="bg-amber-50 p-6 rounded-2xl border border-amber-100">
            <h2 className="text-2xl font-bold text-amber-800 mb-4">NOT MEDICAL ADVICE</h2>
            <p className="text-amber-900 font-medium">
              The content provided within the HydraFlow mobile application and on this website, including text, graphics, images, and hydration goal calculations, is for informational purposes only. It is NOT intended to be a substitute for professional medical advice, diagnosis, or treatment.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-800 mb-4">Individual Variations</h2>
            <p>
              Hydration requirements vary significantly based on body weight, age, activity level, climate, and overall health status. The algorithms used by HydraFlow are based on general clinical hydration models and may not be suitable for individuals with specific medical conditions.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-800 mb-4">Consult Your Physician</h2>
            <p>
              Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition. Never disregard professional medical advice or delay in seeking it because of something you have read on the HydraFlow platform.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-800 mb-4">Kidney & Chronic Conditions</h2>
            <p>
              If you have chronic kidney disease (CKD), heart failure, or any condition where fluid intake must be strictly monitored or restricted, you should strictly follow the guidance of your healthcare provider and NOT follow the automated goals generated by this application.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-800 mb-4">No Physician-Patient Relationship</h2>
            <p>
              The use of HydraFlow does not create a physician-patient relationship between you and the developers of the application.
            </p>
          </section>
        </div>

        <div className="mt-16 pt-8 border-t border-gray-100 text-center">
          <p className="text-gray-400 text-sm">© 2026 HydraFlow. All rights reserved.</p>
        </div>
      </div>
    </div>
  );
}
