import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';

final localeProvider = StateProvider<Locale>((ref) {
  final box = Hive.box('hydraflow_prefs');
  final langCode = box.get('language', defaultValue: 'en') as String;
  
  ref.listenSelf((previous, next) {
    box.put('language', next.languageCode);
  });

  return Locale(langCode);
});

class AppStrings {
  static Map<String, Map<String, String>> translations = {
    'en': {
      'app_name': 'HydraFlow',
      'tagline': 'Stay Hydrated. Stay Focused.',
      'welcome': 'Welcome to HydraFlow',
      'get_started': 'Get Started',
      'next': 'Next',
      'back': 'Back',
      'save': 'Save',
      'settings': 'Settings',
      'language': 'Language',
      'english': 'English',
      'indonesian': 'Indonesian',
      'hydration_goal': 'Hydration Goal',
      'add_water': 'Add Water',
      'log_water': 'Log Water',
      'daily_progress': 'Daily Progress',
      'history': 'History',
      'reminders': 'Reminders',
      'achievements': 'Achievements',
      'profile': 'Profile',
      'edit_profile': 'Edit Profile',
      'name': 'Name',
      'weight': 'Weight',
      'activity_level': 'Activity Level',
      'hot_climate': 'Hot Climate',
      'yes': 'Yes',
      'no': 'No',
      'save_log': 'SAVE LOG',
      'log_success': 'Hydration Logged!',
      'units': 'Units',
      'preferences': 'Preferences',
      'help_support': 'Help & Support',
      'account_data': 'Account & Data',
      'logout': 'Logout',
      'delete_account': 'Delete Account',
      'reset_data': 'Reset All Data',
      'confirm_reset': 'Are you sure you want to reset all your data?',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      // Onboarding
      'onboarding_1_title': 'Science of Hydration',
      'onboarding_1_sub': 'Your body is 60% water',
      'onboarding_1_body': 'Staying properly hydrated boosts energy, improves focus, and supports every cell in your body. Most people fall short — HydraFlow changes that.',
      'onboarding_2_title': 'Your Personal Plan',
      'onboarding_2_sub': 'Calculated just for you',
      'onboarding_2_body': 'Answer a few quick questions about your weight and activity level. HydraFlow calculates a scientifically-backed hydration target tailored to you.',
      'onboarding_3_title': 'Smart Reminders',
      'onboarding_3_sub': 'Adaptive nudges',
      'onboarding_3_body': 'Our intelligent reminder engine adapts throughout the day — gentle in the morning, active at midday, and motivating in the evening.',
      'onboarding_4_title': 'Privacy First',
      'onboarding_4_sub': 'Your data, your control',
      'onboarding_4_body': 'We use your weight only to calculate hydration goals — everything is stored 100% offline on your device. Never shared or sold.',
      'onboarding_5_title': 'Success Signals',
      'onboarding_5_sub': 'Critical for habit building',
      'onboarding_5_body': 'To keep you on track, HydraFlow sends gentle nudges. We politely request notification access next to ensure you never miss a window.',
      'skip': 'Skip',
      'start_assessment': 'Start My Scientific Assessment',
      // Disclaimer
      'safety_transparency': 'Safety & Transparency',
      'disclaimer_body': 'HydraFlow is a hydration habit builder. By continuing, you acknowledge our data policies and medical disclaimers.',
      'clinical_standard': 'Clinical Standard Basis',
      'clinical_desc': 'HydraFlow calculation models are based on population standards from the National Academies of Medicine (NAM) and WHO guidelines.',
      'transparent_erasure': 'Transparent Data Erasure',
      'erasure_desc': 'We prioritize your privacy. You can export your data or delete your entire account permanently at any time via Settings.',
      'agree_terms_start': 'I have read and agree to the ',
      'agree_terms_mid': 'Terms of Service',
      'agree_terms_end': 'Privacy Policy',
      'continue_hf': 'Continue into HydraFlow',
      // New Strings
      'hello': 'Hello',
      'time_to_hydrate': 'Time to hydrate your body',
      'daily_history': 'Daily History',
      'view_all': 'View All',
      'no_logs_today': 'No logs yet today',
      'every_drop_counts': 'Every drop counts! Start your hydration journey now.',
      'streak': 'Streak',
      'rank': 'Rank',
      'efficiency': 'Efficiency',
      'bio_tip': 'Bio-Tip',
      'days': 'Days',
      'goal_reached': 'GOAL REACHED!',
      'optimal_hydration': 'Hydration levels are optimal.\nYour body thanks you!',
      'continue': 'CONTINUE',
      'almost_there': 'Almost There',
      'complete_profile_desc': 'Complete your profile to personalize your hydration journey.',
      'finalize_setup': 'Complete Setup',
      'step': 'Step',
      'of': 'of',
      'calculate_plan': 'Calculate My Plan',
      'tell_us_about_you': 'Tell us about yourself',
      'bio_profile_desc': 'Your biological profile helps us establish a baseline.',
      'medical_transparency': 'Medical Transparency',
      'medical_desc': 'HydraFlow is a wellness tool. Targets are population-based and not medical advice.',
      'consistency_key': 'Consistency is Key',
      'reminder_desc': 'HydraFlow sends gentle reminders based on your activity and goals.',
      'allow_reminders': 'Allow Smart Reminders',
      'maybe_later': 'Maybe later',
      'smart_intervals': 'Smart Intervals (AI Spacing)',
      'quiet_hours_desc': 'Quiet Hours (No night pings)',
      'goal_driven': 'Goal-Driven (Adaptive nudges)',
      // Quiz
      'step_of': 'Step %s of %s',
      'medical_desc_quiz': 'HydraFlow is a wellness tool. The calculated targets are based on general population data and should not replace professional medical advice.',
      'agreement_quiz': 'By continuing, you agree to our Terms and emphasize that you have no restrictive medical conditions.',
      'biometrics_title': 'Tell us about yourself',
      'biometrics_desc': 'Your biological profile helps us establish a baseline.',
      'activity_level_quiz': 'Daily Activity Level',
      'sedentary_desc': 'Minimal movement, office work',
      'moderate_desc': 'Regular walking/light exercise',
      'active_desc': 'Intense exercise or physical labor',
      'environment_title': 'Your Environment',
      'moderate_climate': 'Moderate',
      'hot_humid_climate_quiz': 'Hot / Humid',
      'climate_desc': 'We adjust your target based on fluid loss through perspiration.',
      'objective_title': 'Your Goal',
      'cognitive_focus': 'Cognitive Focus',
      'energy_levels': 'Energy Levels',
      'skin_health': 'Skin Health',
      'general_health': 'General Health',
      'hf_intelligence': 'HydraFlow Intelligence',
      'analyzing_biometrics': 'Analyzing Biometrics...',
      'calibrating_env': 'Calibrating Environment...',
      'mapping_activity': 'Mapping Activity Levels...',
      'optimizing_targets': 'Optimizing Fluid Targets...',
      'finalizing_plan': 'Finalizing HydraFlow Plan...',
      // Analytics
      'analytics': 'Analytics',
      'your_hydration_story': 'Your Hydration Story',
      'detailed_breakdown': 'Detailed breakdown of your habits',
      'hydration_velocity': 'Hydration Velocity',
      'last_7_days': 'Last 7 calendar days',
      'weekly_average': 'Weekly Average',
      'best_day': 'Best Day',
      'goal_hit_rate': 'Goal Hit Rate',
      'this_month': 'This Month',
      'goal_met': 'Goal Met',
      'incomplete': 'Incomplete',
      'science_refs': 'Science & References',
      'science_backed': 'Science-Backed Hydration',
      'important_medical': 'Important: This wellness tool indicates population-based hydration targets and does not replace medical diagnosis.',
      'keep_it_up': 'Keep it up!',
      'start_streak': 'Start your streak!',
      'beginner': 'Beginner',
      'intermediate': 'Intermediate',
      'expert': 'Expert',
      'master': 'Master',
      // Reminders
      'smart_reminders': 'Smart Reminders',
      'notification_settings': 'Notification Settings',
      'quiet_hours': 'Quiet Hours',
      'interval': 'Interval',
      'minutes': 'minutes',
      'active': 'Active',
      'disabled': 'Disabled',
      'adaptive_nudges': 'Adaptive nudges based on behavior',
      'interval_tuning': 'Interval Tuning',
      'active_window': 'Active Window',
      'wake': 'Wake',
      'sleep': 'Sleep',
      'sync_intervals': 'Synchronize Intervals',
      'reminders_paused': 'Reminders Paused',
      'no_nudges_desc': "You won't receive hydration nudges.",
      'reminders_sync_success': 'Hydration reminders synchronized 💧',
      // Achievements
      'reward_points': 'Reward Points',
      'pts': 'PTS',
      'lvl': 'LVL',
      'first_drop': 'First Drop',
      'hydrator': 'Hydrator',
      'consistent': 'Consistent',
      'ocean_master': 'Ocean Master',
      'flow_state': 'Flow State',
      'aquaman': 'Aquaman',
      'logged_first': 'Logged first intake',
      'drank_5l': 'Drank 5L total',
      'drank_10l': 'Drank 10L total',
      'drank_50l': 'Drank 50L total',
      'drank_100l': 'Drank 100L total',
      'drank_500l': 'Drank 500L total',
      // Profile
      'basic_info': 'Basic Info',
      'display_name': 'Display Name',
      'age': 'Age',
      'weight_kg': 'Weight (kg)',
      'lifestyle_env': 'Lifestyle & Environment',
      'sedentary': 'Sedentary',
      'moderate': 'Moderate',
      'active_lvl': 'Active',
      'hot_humid_climate': 'Hot / Humid Climate',
      'hot_humid_desc': 'Increase targets for sweat compensation',
      'calculated_daily_goal': 'Calculated Daily Goal',
      'ml_per_day': 'ml / day',
      'save_profile_changes': 'Save Profile Changes',
      'profile_updated': 'Profile updated successfully!',
      'error_saving_profile': 'Error saving profile',
      'enter_name': 'Enter name',
      // Settings Extra
      'faq_kb': 'FAQ & Knowledge Base',
      'contact_support': 'Contact Support',
      'download_my_data': 'Download My Data',
      'clear_local_cache': 'Clear Local Cache',
      'upgrade_pro': 'Upgrade to HydraFlow Pro',
      'restore_purchases': 'Restore Previous Purchases',
      'privacy_policy': 'Privacy Policy',
      'terms_of_service': 'Terms of Service',
      'medical_disclaimer': 'Medical Disclaimer',
      'legal_compliance': 'Legal & Compliance',
      'danger_zone': 'Danger Zone',
      'exporting_data': 'Generating secure JSON export...',
      'data_exported': 'Comprehensive data package exported to clipboard.',
      'cache_cleared': 'Local cache cleared.',
      'premium_features': 'HydraFlow Premium',
      'recorded': 'recorded',
      'error': 'Error',
    },
    'id': {
      'app_name': 'HydraFlow',
      'tagline': 'Tetap Terhidrasi. Tetap Fokus.',
      'welcome': 'Selamat Datang di HydraFlow',
      'get_started': 'Mulai Sekarang',
      'next': 'Lanjut',
      'back': 'Kembali',
      'save': 'Simpan',
      'settings': 'Pengaturan',
      'language': 'Bahasa',
      'english': 'Inggris',
      'indonesian': 'Indonesia',
      'hydration_goal': 'Target Hidrasi',
      'add_water': 'Tambah Air',
      'log_water': 'Catat Minum',
      'daily_progress': 'Progres Harian',
      'history': 'Riwayat',
      'reminders': 'Pengingat',
      'achievements': 'Pencapaian',
      'profile': 'Profil',
      'edit_profile': 'Edit Profil',
      'name': 'Nama',
      'weight': 'Berat Badan',
      'activity_level': 'Tingkat Aktivitas',
      'hot_climate': 'Cuaca Panas',
      'yes': 'Ya',
      'no': 'Tidak',
      'save_log': 'SIMPAN CATATAN',
      'log_success': 'Air Dicatat!',
      'units': 'Satuan',
      'preferences': 'Preferensi',
      'help_support': 'Bantuan & Dukungan',
      'account_data': 'Akun & Data',
      'logout': 'Keluar',
      'delete_account': 'Hapus Akun',
      'reset_data': 'Hapus Semua Data',
      'confirm_reset': 'Apakah Anda yakin ingin menghapus semua data Anda?',
      'cancel': 'Batal',
      'confirm': 'Konfirmasi',
      // Onboarding
      'onboarding_1_title': 'Sains Hidrasi',
      'onboarding_1_sub': 'Tubuh Anda adalah 60% air',
      'onboarding_1_body': 'Terhidrasi dengan baik meningkatkan energi, fokus, dan mendukung setiap sel tubuh. Kebanyakan orang kekurangan — HydraFlow mengubah itu.',
      'onboarding_2_title': 'Rencana Pribadi Anda',
      'onboarding_2_sub': 'Dihitung khusus untuk Anda',
      'onboarding_2_body': 'Jawab beberapa pertanyaan tentang berat badan dan aktivitas. HydraFlow menghitung target hidrasi ilmiah yang disesuaikan untuk Anda.',
      'onboarding_3_title': 'Pengingat Pintar',
      'onboarding_3_sub': 'Nudge adaptif',
      'onboarding_3_body': 'Mesin pengingat cerdas kami beradaptasi sepanjang hari — lembut di pagi hari, aktif di siang hari, dan memotivasi di malam hari.',
      'onboarding_4_title': 'Privasi Utama',
      'onboarding_4_sub': 'Data Anda, kendali Anda',
      'onboarding_4_body': 'Kami menggunakan berat badan hanya untuk hitung target — semua disimpan 100% offline di perangkat Anda. Tidak pernah dibagikan atau dijual.',
      'onboarding_5_title': 'Sinyal Sukses',
      'onboarding_5_sub': 'Kritis untuk bangun kebiasaan',
      'onboarding_5_body': 'Untuk menjaga Anda tetap pada jalur, HydraFlow mengirim pengingat lembut. Kami meminta akses notifikasi untuk memastikan jendela hidrasi tidak terlewat.',
      'skip': 'Lewati',
      'start_assessment': 'Mulai Penilaian Ilmiah Saya',
      // Disclaimer
      'safety_transparency': 'Keamanan & Transparansi',
      'disclaimer_body': 'HydraFlow adalah pembangun kebiasaan hidrasi. Dengan melanjutkan, Anda mengakui kebijakan data dan sanggahan medis kami.',
      'clinical_standard': 'Basis Standar Klinis',
      'clinical_desc': 'Model perhitungan HydraFlow didasarkan pada standar populasi dari National Academies of Medicine (NAM) dan pedoman WHO.',
      'transparent_erasure': 'Penghapusan Data Transparan',
      'erasure_desc': 'Kami mengutamakan privasi Anda. Anda dapat mengekspor data atau menghapus seluruh akun secara permanen kapan saja melalui Pengaturan.',
      'agree_terms_start': 'Saya telah membaca dan menyetujui ',
      'agree_terms_mid': 'Ketentuan Layanan',
      'agree_terms_end': 'Kebijakan Privasi',
      'continue_hf': 'Lanjutkan ke HydraFlow',
      // New Strings
      'hello': 'Halo',
      'time_to_hydrate': 'Waktunya menghidrasi tubuhmu',
      'daily_history': 'Riwayat Harian',
      'view_all': 'Lihat Semua',
      'no_logs_today': 'Belum ada catatan hari ini',
      'every_drop_counts': 'Setiap tetes berharga! Mulai hidrasimu sekarang.',
      'streak': 'Runtun',
      'rank': 'Peringkat',
      'efficiency': 'Efisiensi',
      'bio_tip': 'Tips Bio',
      'days': 'Hari',
      'goal_reached': 'TARGET TERCAPAI!',
      'optimal_hydration': 'Level hidrasi optimal.\nTubuhmu berterima kasih!',
      'continue': 'LANJUTKAN',
      'almost_there': 'Hampir Selesai',
      'complete_profile_desc': 'Lengkapi profilmu untuk personalisasi hidrasi.',
      'finalize_setup': 'Selesaikan Pengaturan',
      'step': 'Langkah',
      'of': 'dari',
      'calculate_plan': 'Hitung Rencanaku',
      'tell_us_about_you': 'Beritahu tentang dirimu',
      'bio_profile_desc': 'Profil biologismu membantu kami menetapkan target awal.',
      'medical_transparency': 'Transparansi Medis',
      'medical_desc': 'HydraFlow adalah alat kesehatan. Target bersifat umum dan bukan saran medis.',
      'consistency_key': 'Konsistensi adalah Kunci',
      'reminder_desc': 'HydraFlow mengirim pengingat lembut berdasarkan aktivitas dan targetmu.',
      'allow_reminders': 'Izinkan Pengingat Pintar',
      'maybe_later': 'Mungkin nanti',
      'smart_intervals': 'Interval Pintar (Jeda AI)',
      'quiet_hours_desc': 'Jam Tenang (Tanpa gangguan malam)',
      'goal_driven': 'Berbasis Target (Nudge adaptif)',
      // Quiz
      'step_of': 'Langkah %s dari %s',
      'medical_desc_quiz': 'HydraFlow adalah alat kesehatan. Target yang dihitung berdasarkan data populasi umum dan tidak menggantikan saran medis profesional.',
      'agreement_quiz': 'Dengan melanjutkan, Anda menyetujui Ketentuan kami dan menegaskan bahwa Anda tidak memiliki kondisi medis yang membatasi.',
      'biometrics_title': 'Beritahu tentang dirimu',
      'biometrics_desc': 'Profil biologismu membantu kami menetapkan target awal.',
      'activity_level_quiz': 'Tingkat Aktivitas Harian',
      'sedentary_desc': 'Gerakan minimal, pekerjaan kantor',
      'moderate_desc': 'Jalan santai/olahraga ringan teratur',
      'active_desc': 'Olahraga intens atau kerja fisik berat',
      'environment_title': 'Lingkungan Anda',
      'moderate_climate': 'Moderat',
      'hot_humid_climate_quiz': 'Panas / Lembab',
      'climate_desc': 'Kami menyesuaikan target berdasarkan kehilangan cairan melalui keringat.',
      'objective_title': 'Target Anda',
      'cognitive_focus': 'Fokus Kognitif',
      'energy_levels': 'Tingkat Energi',
      'skin_health': 'Kesehatan Kulit',
      'general_health': 'Kesehatan Umum',
      'hf_intelligence': 'Kecerdasan HydraFlow',
      'analyzing_biometrics': 'Menganalisis Biometrik...',
      'calibrating_env': 'Kalibrasi Lingkungan...',
      'mapping_activity': 'Pemetaan Tingkat Aktivitas...',
      'optimizing_targets': 'Optimasi Target Cairan...',
      'finalizing_plan': 'Finalisasi Rencana HydraFlow...',
      // Analytics
      'analytics': 'Analitik',
      'your_hydration_story': 'Kisah Hidrasimu',
      'detailed_breakdown': 'Rincian detail kebiasaanmu',
      'hydration_velocity': 'Kecepatan Hidrasi',
      'last_7_days': '7 hari kalender terakhir',
      'weekly_average': 'Rata-rata Mingguan',
      'best_day': 'Hari Terbaik',
      'goal_hit_rate': 'Tingkat Capaian Target',
      'this_month': 'Bulan Ini',
      'goal_met': 'Target Tercapai',
      'incomplete': 'Belum Selesai',
      'science_refs': 'Sains & Referensi',
      'science_backed': 'Hidrasi Berbasis Sains',
      'important_medical': 'Penting: Alat kebugaran ini menunjukkan target hidrasi berbasis populasi dan tidak menggantikan diagnosis medis.',
      'keep_it_up': 'Teruskan!',
      'start_streak': 'Mulai rincianmu!',
      'beginner': 'Pemula',
      'intermediate': 'Menengah',
      'expert': 'Ahli',
      'master': 'Master',
      // Reminders
      'smart_reminders': 'Pengingat Pintar',
      'notification_settings': 'Pengaturan Notifikasi',
      'quiet_hours': 'Jam Tenang',
      'interval': 'Interval',
      'minutes': 'menit',
      'active': 'Aktif',
      'disabled': 'Nonaktif',
      'adaptive_nudges': 'Pengingat adaptif berdasarkan perilaku',
      'interval_tuning': 'Penyetelan Interval',
      'active_window': 'Jendela Aktif',
      'wake': 'Bangun',
      'sleep': 'Tidur',
      'sync_intervals': 'Sinkronkan Interval',
      'reminders_paused': 'Pengingat Jeda',
      'no_nudges_desc': "Anda tidak akan menerima pengingat hidrasi.",
      'reminders_sync_success': 'Pengingat hidrasi disinkronkan 💧',
      // Achievements
      'reward_points': 'Poin Hadiah',
      'pts': 'PTS',
      'lvl': 'LVL',
      'first_drop': 'Tetes Pertama',
      'hydrator': 'Hydrator',
      'consistent': 'Konsisten',
      'ocean_master': 'Master Samudra',
      'flow_state': 'Keadaan Mengalir',
      'aquaman': 'Aquaman',
      'logged_first': 'Mencatat minum pertama',
      'drank_5l': 'Minum total 5L',
      'drank_10l': 'Minum total 10L',
      'drank_50l': 'Minum total 50L',
      'drank_100l': 'Minum total 100L',
      'drank_500l': 'Minum total 500L',
      // Profile
      'basic_info': 'Info Dasar',
      'display_name': 'Nama Tampilan',
      'age': 'Usia',
      'weight_kg': 'Berat (kg)',
      'lifestyle_env': 'Gaya Hidup & Lingkungan',
      'sedentary': 'Sedenter',
      'moderate': 'Moderat',
      'active_lvl': 'Aktif',
      'hot_humid_climate': 'Cuaca Panas / Lembab',
      'hot_humid_desc': 'Tingkatkan target untuk kompensasi keringat',
      'calculated_daily_goal': 'Target Harian Dihitung',
      'ml_per_day': 'ml / hari',
      'save_profile_changes': 'Simpan Perubahan Profil',
      'profile_updated': 'Profil berhasil diperbarui!',
      'error_saving_profile': 'Gagal menyimpan profil',
      'enter_name': 'Masukkan nama',
      // Settings Extra
      'faq_kb': 'FAQ & Basis Pengetahuan',
      'contact_support': 'Hubungi Dukungan',
      'download_my_data': 'Unduh Data Saya',
      'clear_local_cache': 'Hapus Cache Lokal',
      'upgrade_pro': 'Tingkatkan ke HydraFlow Pro',
      'restore_purchases': 'Pulihkan Pembelian Sebelumnya',
      'privacy_policy': 'Kebijakan Privasi',
      'terms_of_service': 'Ketentuan Layanan',
      'medical_disclaimer': 'Sanggahan Medis',
      'legal_compliance': 'Hukum & Kepatuhan',
      'danger_zone': 'Zona Bahaya',
      'exporting_data': 'Menghasilkan ekspor JSON aman...',
      'data_exported': 'Paket data lengkap disalin ke clipboard.',
      'cache_cleared': 'Cache lokal dihapus.',
      'premium_features': 'HydraFlow Premium',
      'recorded': 'dicatat',
      'error': 'Kesalahan',
    }
  };

  static String get(String key, WidgetRef ref) {
    final locale = ref.watch(localeProvider);
    return translations[locale.languageCode]?[key] ?? key;
  }
}
